version: "3"

services:
#  stardog:
#    image: ${DOCKER_REGISTRY}/stardog:${TAG}
##    restart: always
#    build:
#      args:
#        - STARDOG_VERSION=${STARDOG_VERSION}
#    environment:
#     - STARDOG_JAVA_ARGS=-Xms3g -Xmx3g -XX:MaxDirectMemorySize=8g
##     - STARDOG_FLAGS=--upgrade
#    ports:
#      - "127.0.0.1:5820:5820"
#    volumes:
#      - ${DOCKER_BASE_DIR}/stardog:/home/stardog/data
#      - $PWD/stardog/production-license:/production-license
#    networks:
#      - platform

#  elasticsearch:
#    image: ${DOCKER_REGISTRY}/elasticsearch:${TAG}
##    restart: always
#    environment:
##     - cluster.name=docker-cluster
##     - bootstrap.memory_lock=true
#     - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
#    ports:
#      - "127.0.0.1:9300:9300"
#      - "127.0.0.1:9200:9200"
#    volumes:
#      - ${DOCKER_BASE_DIR}/elasticsearch:/usr/share/elasticsearch/data
#    networks:
#      - platform

  elasticsearchlogs:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    restart: always
    environment:
    - cluster.name=nextgen-logs
    volumes:
     - elasticsearchlogs:/usr/share/elasticsearch/data
    networks:
      - platform

  kibana:
    image: ${DOCKER_REGISTRY}/nextgen/kibana:${TAG}
#    restart: always
    ports:
      - "127.0.0.1:5601:5601"
    depends_on:
      - elasticsearchlogs
    networks:
      - platform

  fluentd:
    image: ${DOCKER_REGISTRY}/nextgen/fluentd:${TAG}
    restart: always
    ports:
      - "127.0.0.1:24224:24224"
      - "127.0.0.1:24224:24224/udp"
    depends_on:
      - elasticsearchlogs
    networks:
      - platform
      - client
    volumes:
      - fluentd:/fluentd/log

  nginx:
    image: ${DOCKER_REGISTRY}/nextgen/nginx:${TAG}
#    restart: always
    ports:
      - "80:80"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: nginx.combined
    depends_on:
      - fluentd
    networks:
      - platform
      - client

#  gitserver:
#    image: ${DOCKER_REGISTRY}/nextgen/git-server:${TAG}
#    restart: always
#    ports:
#      - "127.0.0.1:2222:22"
#    volumes:
#      - ${GIT_SERVER_KEYS}:/git-server/keys
#      - git-server-repos:/git-server/repos
#    networks:
#      - platform

  hazelcast:
#    image: hazelcast/hazelcast
    image: ${DOCKER_REGISTRY}/nextgen/hazelcast:${TAG}
#    restart: always
    environment:
      - CLASSPATH=/opt/hazelcast/lib
      - JAVA_OPTS= -Xms512M -Xmx1024M -Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast.xml -Dhazelcast.logging.type=slf4j -Dlogback.configurationFile=/opt/hazelcast/config_ext/logback.xml
    depends_on:
      - fluentd
    volumes:
      - ./docker/hazelcast/config_ext:/opt/hazelcast/config_ext
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: hazelcast
    networks:
      - platform

#  vertx-test:
#    image: ${DOCKER_REGISTRY}/nextgen/vertx-test:${TAG}
#    networks:
#      - platform

#  vertx-fatjar-test:
#    image: ${DOCKER_REGISTRY}/nextgen/vertx-fatjar-test:${TAG}
#    networks:
#      - platform

  api:
    image: ${DOCKER_REGISTRY}/nextgen/api:${TAG}
#    restart: always
    environment:
      - BASE_URL=${BASE_URL}
    ports:
      - "127.0.0.1:8180:8080"
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: component.all
    networks:
      platform:

  frontend:
    image: ${DOCKER_REGISTRY}/nextgen/frontend:${TAG}
#    restart: always
    networks:
      platform:

volumes:
  fluentd:
  elasticsearchlogs:

networks:
  platform:
  client:
