package com.generator.generators.templates.domain;

/**
 * goe on 5/11/16.
 */
public enum TemplateEntities {

	TEMPLATEFILE, TEMPLATEIMPORT, TEMPLATESTATEMENT, TEMPLATEPARAMETER, STATEMENT, STRINGPROPERTY, BOOLEANPROPERTY, ENUMPROPERTY, KEYVALUELISTPROPERTY, LISTPROPERTY, STATEMENTPROPERTY, PROPERTYSET, GENERATEDFILE
}