package com.generator.generators.java.domain;

/**
 * User: goe
 * Date: 24.10.13
 */
public enum JavaRelation {

   EXTENDS

   /*ABSTRACT, CONTINUE, FOR, NEW, SWITCH, ASSERT, DEFAULT, GOTO, PACKAGE, SYNCHRONIZED, BOOLEAN, DO, IF, PRIVATE,
THIS, BREAK, DOUBLE, IMPLEMENTS, PROTECTED, THROW, BYTE, ELSE, IMPORT, PUBLIC, THROWS, CASE, ENUM, INSTANCEOF,
RETURN, TRANSIENT, CATCH, EXTENDS, INT, SHORT, TRY, CHAR, FINAL, INTERFACE, STATIC, VOID, CLASS, FINALLY, LONG,
STRICTFP, VOLATILE, CONST, FLOAT, NATIVE, SUPER, WHILE*/

}